[tools]
atuin = "latest"
bat = "latest"
btop = "latest"
caddy = "latest"
cheat = "latest"
eza = "latest"
fzf = "latest"
git-lfs = "latest"
github-cli = "latest"
jj = "latest"
kompose = "latest"
node = "latest"
restic = "latest"
"ubi:docker/compose" = { version = "latest", exe = "compose", rename_exe = "docker-compose" }
"ubi:ouch-org/ouch" = "latest"
yazi = "latest"
zoxide = "latest"

[settings]
idiomatic_version_file_enable_tools = ["node"]
