[mgr]
sort_by = "mtime"
sort_reverse = true
linemode = "mtime"
show_hidden = true

[[plugin.prepend_previewers]]
mime = "application/{*zip,tar,bzip2,7z*,rar,xz,zstd,java-archive}"
run  = "ouch"

[opener]
extract = [
	{ run = 'ouch d -y "$@"', desc = "Extract here with ouch", for = "unix" },
]
play = [
	{ run = 'flatpak run io.mpv.Mpv "$@"', desc = 'mpv', orphan = true, for = "unix" },
]
codium = [
	{ run = 'codium "$@"', desc = 'codium', orphan = true, for = "unix" }
]
zed = [
	{ run = 'flatpak run dev.zed.Zed "$@"', desc = 'zed', orphan = true, for = "unix" }	
]

[open]
prepend_rules = [
	{ name = "*.html", use = [ "open", "edit" ] },
	{ mime = "inode/directory", use = [ "zed" ] },
]
